project:
  type: website

website:
  google-analytics:
    tracking-id: "G-LML37CZLQM"
  favicon: images/icon.ico
  title: "Jones, Silas & Ward Lab"
  navbar:
    background: primary
    foreground: "white"
    tools: 
      - icon: twitter
        href: https://twitter.com/jones_silas_lab
      - icon: github
        href: https://github.com/JonSilas/JSWlab 
      - icon: mastodon
        href: https://fediscience.org/@JSW_lab 
    left:
      - text: "About"  
        menu: 
          - href: about.qmd
            text: The Lab
          - href: TheTeam.qmd
            text: The Team
          - href: LabLife.qmd
            text: "#LabLife"
      - href: JoinTheLab.qmd
        text: Join
      - href: TakePart.qmd
        text: Participate
      - text: "Resources"
        menu: 
        - href: Videos.qmd
          text: Videos
        - href: courses.qmd
          text: Online Materials
        - href: poster.qmd
          text: Talks & Posters
      - href: Workshops.qmd
        text: Workshops
      - href: Publications.qmd
        text: Publications        
      - href: ContactUs.qmd 
        text: Contact Us
format:
  html:
    link-external-newwindow: true
    theme: cyborg
    backgroundcolor: black
    css: styles.css
    toc: true

resources:
  - CNAME


editor: source

