---
toc: false
---
Google Scholar links: [Alex](https://scholar.google.co.uk/citations?user=heLtmbIAAAAJ&hl=en),  [Jon](https://scholar.google.co.uk/citations?user=mMkcfasAAAAJ&hl=en), [Emma](https://scholar.google.co.uk/citations?user=Rvu7U18AAAAJ&hl=en&oi=ao)  

## Papers and chapters

### 2024

Korko, M., Bose, A., **Jones, A.**, Coulson, M., & de Mornay Davies, P. Do words compete as we speak? A systematic review of picture-word interference (PWI) studies investigating the nature of lexical selection. Psychology of Language and Communication, 28(1), 261-322.<https://doi.org/10.58734/plc-2024-0011>

Townsend, P. H., **Jones, A.**, Patel, A. D., & Race, E. (2024). Rhythmic Temporal Cues Coordinate Cross-frequency Phase-amplitude Coupling during Memory Encoding. Journal of Cognitive Neuroscience, 1-17.<https://doi.org/10.1162/jocn_a_02217>

**Ward, E. V.** (2024). Age differences in priming as a function of processing at encoding. Consciousness and Cognition, 117, 103626.<https://doi.org/10.1016/j.concog.2023.103626>

Allegranti, B., & **Silas, J.** (2024). Capoeira in the Wake: Neurofeminism Moves with the Transgenerational. In Moving Kinship (pp. 245-287). Routledge. [ISBN 9780367464905](https://www.routledge.com/Moving-Kinship-Practicing-Feminist-Justice-in-a-More-than-Human-World/Allegranti/p/book/9780367464905)

Korko, M., Coulson, M., **Jones, A.**, & de Mornay Davies, P. (2024). The many facets of inhibitory control and their role in syntactic selection. Language and Cognition, 16(2), 425-451.<https://doi.org/10.1017/langcog.2023.44>

### 2023

**Jones, A.**, Gandhi, V., Mahiddine, A. Y., & Huyck, C. (2023). Bridging Neuroscience and Robotics: Spiking Neural Networks in Action. Sensors, 23(21), 8880.<https://doi.org/10.3390/s23218880>

**Jones, A., Silas, J., Anderson, W. &  Ward, E. V.** (2023). Null effects of temporal prediction on recognition memory but evidence for differential neural activity at encoding. A registered report, Cortex, ISSN 0010-9452 <https://doi.org/10.1016/j.cortex.2023.09.006>

Korko, M., Coulson, M., **Jones, A.**, & de Mornay Davies, P. (2023). The many facets of inhibitory control and their role in syntactic selection. Language and Cognition, 1-27.<https://doi.org/10.1017/langcog.2023.44>

Ali, S. M., Augusto, J. C., Windridge, D., & **Ward, E.** (2023). A user-guided personalization methodology to facilitate new smart home occupancy. Universal Access in the Information Society, 22(3), 869-891.<https://doi.org/10.1007/s10209-022-00883-x>

Mangiacotti, A., Cipriani, G., **Ward, E.,** Franco, F., & Biasutti, M. (2023). Development and validation of the Music Cognitive Test: A music-based cognitive screening test. Psychology of Music, 51(2), 373-394.<https://doi.org/10.1177/03057356221100851>

**Silas, J., Jones, A.,** Yarrow, K., & **Anderson, W.** (2023). Spatial attention is not affected by alpha or beta transcranial alternating current stimulation: A registered report. Cortex, 164, 33-50.<https://doi.org/10.1016/j.cortex.2023.03.011>

**Ward, E. V.** (2023). Age and processing effects on perceptual and conceptual priming. Quarterly Journal of Experimental Psychology, 76(1), 1-14.<https://doi.org/10.1177/17470218221090128>

### 2022

**Jones, A., Ward, E. V., Csiszer, E. L., & Szymczak, J.** (2022). Temporal expectation improves recognition memory for spatially attended objects.*Journal of Cognitive Neuroscience*, 1-14.<https://doi.org/10.1162/jocn_a_01872>

Ali, S. M., Augusto, J. C., Windridge, D., & **Ward, E.** (2022). A user-guided personalization methodology to facilitate new smart home occupancy. Universal Access in the Information Society, 1-23.<https://doi.org/10.1007/s10209-022-00883-x>

Pearce, D., Gould, R. L., Roughley, M., Reynolds, G., Ward, E. V., Bhome, R., & Reeves, S. (2022). Paranoid and misidentification subtypes of psychosis in dementia. Neuroscience & Biobehavioral Reviews, 104529.<https://doi.org/10.1016/j.neubiorev.2022.104529>

### 2021

**Silas, J., Jones, A.,** Weiss-Cohen, L., & Ayton, P. (2021). The seductive allure of technical language and its effect on covid-19 vaccine beliefs and intentions. *Vaccine*, *39*(52), 7590-7597. <https://doi.org/10.1016/j.vaccine.2021.11.027>

Korko, M., Coulson, **M., Jones**, A., & de Mornay Davies, P. (2021). Types of interference and their resolution in monolingual word production. Acta Psychologica, 214, 103251.<https://doi.org/10.1016/j.actpsy.2021.103251>

**Jones, A**., **Silas, J**., Todd, J., Stewart, A., Acree, M., Coulson, M., & Mehling, W. E. (2021). Exploring the Multidimensional Assessment of Interoceptive Awareness in youth aged 7--17 years. *Journal of Clinical Psychology*. <https://onlinelibrary.wiley.com/doi/10.1002/jclp.23067>

-   To download the MAIA-youth questionnaire and scoring sheet, see the Appendix in the paper, free to download [here](https://onlinelibrary.wiley.com/doi/10.1002/jclp.23067).

**Ward, E. V.**, Isac, A., Donnelly, M., Van Puyvelde, M., & Franco, F. (2021). Memory improvement in aging as a function of exposure to mood-matching music. Acta psychologica, 212, 103206. <https://doi.org/10.1016/j.actpsy.2020.103206>

### 2020

**Ward, E. V.**, Berry, C. J., Shanks, D. R., Moller, P. L., & Czsiser, E. (2020). Aging predicts decline in explicit and implicit memory: A life-span study. Psychological Science, 31(9), 1071-1083.<https://journals.sagepub.com/doi/10.1177/0956797620927648>

### 2019

**Jones, A**., & **Ward, E. V.** (2019). Rhythmic temporal structure at encoding enhances recognition memory. *Journal of Cognitive Neuroscience*, 1-14. <https://doi.org/10.1162/jocn_a_01431>

**Silas, J., Tipple A.**, & **Jones A.** (2019). Event-related alpha desynchronization in touch -- comparing attention and perception, *Neuroscience Letters,* 705, 131-137. <https://doi.org/10.1016/j.neulet.2019.04.058>

Karlinski, M., **Jones, A**., & Forster, B. (2019). Electrophysiological evidence for changes in attentional orienting and selection in functional somatic symptoms. *Clinical Neurophysiology*. 130(1), 85-92, [doi.org/10.1016/j.clinph.2018.09.027](https://doi.org/10.1016/j.clinph.2018.09.027)

**Jones, A**. (2019). Temporal expectancies and rhythmic cueing in touch: The influence of spatial attention. *Cognition*, *182*, 140-150. https://doi.org/10.1016/j.cognition.2018.09.011

### 2018

Mehling, W. E., Acree, M., Stewart, A., **Silas**, **J., & Jones, A.** (2018). The Multidimensional Assessment of Interoceptive Awareness, Version 2 (MAIA-2). PLOS ONE, 13(12), e0208034. <https://doi.org/10.1371/journal.pone.0208034>

Doty, R. L., Tourbier, I., Neff, J. K., **Silas, J**., Turetsky, B., Moberg, P., ... Detre, J. A. (2018). Influences of temporal lobe epilepsy and temporal lobe resection on olfaction. Journal of Neurology, 0(0), 0. 0001 TT-TLE was associated with shorter OERP. <https://doi.org/10.1007/s00415-018-8891-y>

**Jones, A**., Yarrow, K. & Silas, J. (2018). Are alpha oscillations generated by the somatosensory cortex involved in tactile attention? A registered report using transcranial Alternating Current Stimulation (tACS). *Cortex,* Registered report: In Principle Accepted. DOI: 10.17605/OSF.IO/P7AME

### 2017

**Jones, A**,. Hsu Y-F., Granjon, L. and Waszak F. (2017) Temporal expectancies driven by self- and externally generated rhythms, *NeuroImage, 156*, 352-362. <https://doi.org/10.1016/j.neuroimage.2017.05.042>

Singh, N., Huyck, C., Gandhi, V., **Jones, A.** (2017). 'Neuron-Based Control Mechanisms for a Robotic Arm and Hand'. World Academy of Science, Engineering and Technology, International Science Index 122, *International Journal of Computer, Electrical, Automation, Control and Information Engineering,* 11(2), 175 -- 183.

### 2016

**Silas, J**. & Brandt, K.R. (2016). Frontal transcranial Direct Current Stimulation (tDCS) abolishes list-method directed forgetting. Neuroscience Letters. 616, 166-169.

Hadar, A. A., Rowe, P., Di Costa, S., **Jones, A**., & Yarrow, K. (2016). Motor-evoked potentials reveal a motor-cortical readout of evidence accumulation for sensorimotor decisions. *Psychophysiology*. <http://doi.org/10.1111/psyp.12737> (Impact Factor: 3.1)

Forster, B., Tziraki, M., & **Jones, A.** (2016). The attentive homunculus: ERP evidence for somatotopic allocation of attention in tactile search. *Neuropsychologia*, *84*, 158-166. (Impact factor: 4.35)

### 2015

**Jones, A**. (2015). Independent effects of bottom-up temporal expectancy and top-down spatial attention. An audiovisual study using rhythmic cueing. *Frontiers in Integrative Neuroscience.* **8**:96. doi: 10.3389/fnint.2014.00096 (Impact factor: pending)

**Jones, A**. & Forster B. (2015). Body in Mind. *Frontiers in Psychology*. 6:56. doi:10.3389/fpsyg.2015.00056 (Impact factor: 2.8)

Doty, R. L., Nsoesie, M. T., Chung, I., Osman, A., Pawasarat, I., Caulfield, J., Hurtig, H., **Silas, J**., Dubroff, J., Duda, J.E., Ying, G.S., Tekeli, H., Leon-sarmiento, F.E. (2015). Taste function in early stage treated and untreated Parkinson's disease. Journal of neurology, 262(3), 547--57.

### 2014

**Jones, A.** & Forster, B. (2014). Neural correlates of endogenous attention exogenous attention and inhibition of return in touch. *European Journal of Neuroscience*, 40, pp. 2389--2398. doi:10.1111/ejn.12583 (Impact factor: 3.8)

Osman, A. & **Silas, J**. (2014). Electrophysiological measurement of olfactory function. In R. L. Doty (Ed.), Handbook of olfaction and gustation: 3rd edition (pp. 261 -- 277). Hoboken, New Jersey: Wiley Blackwell.

Doty, R. L., Koti, A., O'Hara, T. a, Landy, J., Shin, C., & **Silas, J**. (2014). Correlates of implicit cognitive line length representation in two-dimensional space. Perceptual and motor skills, 119(2), 550--63.

### 2013

**Jones A.,** Hughes G., & Waszak F. (2013). The interaction between attention and motor prediction. An ERP study. *NeuroImage* 83, 533--541. Doi:10.1016/j.neuroimage.2013.07.004 (Impact factor: 6.4)

**Jones A.,** & Forster, B. (2013). Lost in vision: ERP correlates of exogenous tactile attention when engaging in a visual task, *Neuropsychologia, 51,* 675-685. DOI:10.1016/j.neuropsychologia.2013.01.010 (Impact factor: 4.35)

**Jones, A.** &  Forster, B (2013). Independent effects of endogenous and exogenous attention in touch. *Somatosensory and Motor Research, 30*(4), 161-166. DOI: 10.3109/08990220.2013.779243 (Impact factor: 1.1)

### 2012

**Jones, A.,** & Forster, B. (2012) Reflexive attention in touch: An investigation of event related potentials and behavioural responses. *Biological Psychology, 89*, 313-32. DOI: 10.1016/j.biopsycho.2011.11.004 (Impact factor: 3.4)

**Silas, J**., Holmes, A. & Levy, J. (2012). Sensitivity of 'mu' rhythm modulation to the relevance of an observed movement but not to goal congruency. International Journal of Psychophysiology. 85, 168-173.

### 2011

**Silas**, J., Atif, M.A. & Doty, R.L. (2011). Transcranial magnetic stimulation: A treatment for smell and taste dysfunction? American Journal of Otolaryngology, 32, 38-6.

### 2010

**Silas, J**. & Doty, R.L. (2010). No evidence for specific benefit of acupuncture over vitamin B complex in treating persons with olfactory dysfunction. *Otolaryngology,* 134,6034-4.

**Silas, J**., Levy, J.P., Nielsen, M.K., Slade, L. & Holmes, A. (2010) Sex and individual differences in induced and evoked EEG measures of action observation. Neuropsychologia, 48, 2417-2426.

## Conference presentations, abstracts and proceedings

Bezrukova, E., Zaleshin, M.^1^ **Jones, A.,** Butterworth, B, Kovas, Y., Karolis, V.  Complex cortical dynamics in arithmetic problem solving . *25^th^ Annual meeting of the Oganization for Human Brain Mapping*, Rome Italy, June, 2019.

Lindner E., Darriba A., Yang Q., **Jones A**., Waszak F., Desantis A. The temporal dynamics of action-effect prediction: An EEG study. Presented at 3^rd^ Gottingen Meeting of the German Neuroscience Society. March 2019.

**Jones, A.** & **Ward, E. V**. Rhythmic encoding improves recognition memory. Poster presented at the *25^th^ Annual Cognitive Neuroscience Conference (CNS)*, San Francisco USA, March, 2019

**Silas J**., Leniz I., Chinellato E., Forster B., and **Jones A..** Successful classification of attentional tasks by power modulations in the alpha frequency band. Poster presented at the *25^th^ Annual Cognitive Neuroscience Conference (CNS)*, San Francisco USA, March, 2019

**Jones, A**. & **Ward, E. V.** Rhythmic encoding improves recognition memory. Presentation at *British Association for Cognitive Neuroscience (BACN)*, Glasgow, 6-7 Sept. 2018

**Silas J.** and **Jones A.**: Individual peak alpha frequency in touch -- cognitive and methodological implications. Presentation at *British Association for Cognitive Neuroscience (BACN)*, Glasgow, 6-7 Sept. 2018

**Jones A.** & **Silas. J**. Individual peak alpha frequency in touch -- cognitive and methodological implications Poster presented at the *24^th^ Annual Cognitive Neuroscience Conference (CNS)*, Boston USA, March, 2018

**Jones A**.Temporal and spatial attention in touch. Presentation at *1^st^ Conference of Timing Research Forum*, Strasbourg, France (23-25^th^ October, 2017)

**Jones, A.** and Forster. B. (2017). Alpha oscillations during exogenous and endogenous attention in touch. Poster presented at the *24^th^ Annual Cognitive Neuroscience Conference (CNS)*, San Francisco USA, March, 2017

Calvo-Merino, **Jones, A.,** Haggard, P. and Forster. B. (2017). Embodiment and expertise effects on aesthetics judgments. Poster presented at the *24^th^ Annual Cognitive Neuroscience Conference (CNS)*, San Francisco, USA, March, 2017

Forster, B., Karlinski, M. and **Jones, A.** (2017). Somatic symptoms and exogenous attention: an ERP study investigating modality specificity. Poster presented at the *24^th^ Annual Cognitive Neuroscience Conference (CNS)*, San Francisco, USA, March, 2017

Klein, R., D'Entremont, G., **Jones, A.** and Lawrence, M. (2016) Exploring the neural signature of multimodal IOR, presented at the *46^th^ Annual Society for Neuroscience Conference*, San Diego, USA, November 2016.

d'Entremont, G. R., **Jones, A.,** Lawrence, M. A., & Klein, R. M. (2016). Investigating the neural signature of multi-modal inhibition of return. *Journal of Exercise, Movement, and Sport*, *48*(1), 9.

**Jones, A.** Hsu, Y-F., Granjon, L. & Waszak, F. (2016). Temporal expectancies driven by self- and externally generated rhythms*. 23^rd^ Annual* *Cognitive Neuroscience Society Conference*, April, New York City, USA.

Forster B & **Jones A** (2015). Neural correlates of endogenous and exogenous attention in touch: evidence for independent and interdependent mechanisms. *Front. Hum. Neurosci. Conference Abstract: XII International Conference on Cognitive Neuroscience (ICON-XII).* doi: 10.3389/conf.fnhum.2015.217.00142

Yarrow, K., Hadar, A., Rowe, P., Di Costa, S., & **Jones, A.** (2015). Motor-evoked potentials reveal a motor-cortical readout of evidence accumulation for sensorimotor decisions. *Journal of vision*, *15*(12), 49-49. (Published conference abstract)

**Jones, A.** Forster, B. (2015). ERP correlates of tactile search: The N140cc. *22^rd^ Annual* *Cognitive Neuroscience Society Conference*, April, San Francisco, USA.

Calvo-Merino, B., **Jones, A.,** Gillmeister, H. & Forster, B. (2014). Embodied aesthetics is organized in a somatotopic manner: direct evidence from somatosensory ERPs.

*Congress of the International Association of Empirical Aesthetics (IAEA),* New York City, August 22-24, 2014. (Spoken presentation by Dr. Beatriz Calvo-Merino):

**Jones, A.,** Hughes, G., & Waszak, F. (2013) *The interaction between attention and action expectation. An ERP study.* *Journal of Cognitive Neuroscience*, S . p. 115. ISSN 0898-929X

Calvo-Merino, B., **Jones, A**., Gillmeister, H., Tziraki, M., & Forster, B. (2012, August). The influence of experience on aesthetic processing: insight from ballet dancers watching dance postures. In *COGNITIVE PROCESSING* (Vol. 13, pp. S28-S28). TIERGARTENSTRASSE 17, D-69121 HEIDELBERG, GERMANY: SPRINGER HEIDELBERG.

**Jones, A**. (2011). Neural correlates of automatic attention in touch: event related potential and behavioural measures. Presentation given at the 38th *Australasian Experimental Psychology Conference*, Auckland, New Zealand, 28-30 April

**Jones, A.**, & Forster, B. (2010). Neural correlates of automatic attention in touch: event related potential and behavioural measures. *Psychophysiology* 47: S53 (Conference proceedings)

**Jones, A**. & Forster, B. (2010). Exogenous tactile attention in detection and discrimination task: ERPs and behavioural measures. Poster presented at the 17^th^ *Annual Cognitive Neuroscience Society Meeting,* Montreal, Canada.

Allegranti, B. & **Silas**, J (2014). Embodied Signatures. Presented at Embodied Social Justice conference, London

Allegranti, B. & **Silas**, J (2014). What Moves Us? Presented at Embodied research Methodologies Symposium, London

**Silas**, J., Levy, J. & Crossman (2012). Varying the goal-directed plausibility of observed actions causes differences in mirror neuron system activation. Presented at Cognitive Neuroscience Society, Chicago.

**Silas**, J., Levy, J., Nielsen, M.K., Slade, L. & Holmes, A. (2009) Induced and Evoked Sex Differences in EEG Measures of a Perception/Action Matching system. Presented at Cognitive Neuroscience Society, San Francisco.

**Silas**, J., Levy, J., Holmes, A., Nielsen., M.K. & Slade., L. (2008). Sex differences modulate a perception/action matching system as indexed by EEG power. Presented at Young Physiologists Symposium at Cambridge University.

**Silas**, J., Levy, J., Homles., A., Nielsen., M.K. & Slade., L. (2008). Induced and evoked sex differences in EEG measures of a perception/action matching system. Presented at British Association of Cognitive Neuroscience annual meeting at Swansea University.

Hogan, E., Slade, L., Nielsen, M.K., Levy, J.P., Holmes, A & **Silas**, J. (2008). Top-down Intention Understanding and EEG Mu Rhythm during Observation of A not B Task in Adults: Links with "Theory of Mind". Presented at British Association of Cognitive Neuroscience conference.

**Silas**, J., Hodges, T., Holmes, A., Judson, H., Levy, J., Nielsen, M., & Slade, L. (2007). Sex and Individual Differences Modulate a Perception/Action Matching System as Indexed by EEG Power. Presented at British Association of Cognitive Neuroscience conference. *Awarded high commendation.*

**Silas**, J. & Hegarty, P. (2006). The role of suppression in causal reasoning: A new account of prejudice expression towards heroin users. Presented at Wessex & Wight Undergraduate/Postgraduate Student Psychology Conference.
